module SashimiTanpopo
  module Provider
    class Local < Base
      def initialize: (
          recipe_paths: Array[String],
          target_dir: String,
          params: Hash[Symbol, String],
          dry_run: bool,
          is_colored: bool
        ) -> void

      def perform: () -> void
    end
  end
end
