module SashimiTanpopo
  class CLI < Thor
    def self.exit_on_failure?: () -> bool

    def self.define_common_options: () -> void

    def self.parse_params: (Array[String] params) -> Hash[Symbol, String]

    def version: () -> void

    def local: (*String recipe_files) -> void

    def github: (*String recipe_files) -> void

    def option_or_env: (
        (String | Symbol) option_name,
        String env_name,
        ?String? default,
      ) -> String?

    def option_or_env!: (
        (String | Symbol) option_name,
        String env_name,
      ) -> String
  end
end
