module SashimiTanpopo
  class FileUpdater
    def perform: (
        recipe_path: String,
        target_dir: String,
        params: Hash[Symbol, String],
        dry_run: bool,
        is_colored: bool,
      ) -> Array[String]

    def evaluate: (
        recipe_body: String,
        recipe_path: String,
        target_dir: String,
        params: Hash[Symbol, String],
        dry_run: bool,
        is_colored: bool,
      ) -> Array[String]

    class EvalContext
      attr_reader params: Hash[Symbol, String]

      attr_reader changed_file_paths: Array[String]

      def initialize: (
          params: Hash[Symbol, String],
          dry_run: bool,
          is_colored: bool,
        ) -> void

      def update_file: (String pattern) { (String) -> String } -> void

      private

      def update_single_file: (String path) { (String) -> String } -> bool

      def show_diff: (String str1, String str2) -> void
    end

    class InstanceEval
      def initialize: (
          recipe_body: String,
          recipe_path: String,
          target_dir: String,
          context: EvalContext
        ) -> void

      def call: () -> Array[String]
    end
  end
end
